### ISSUE TITLE
请问下载的歌词保存到哪里去了呢

### ISSUE THREAD

**Issue by eklim530** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#1]
您好，感谢您的辛勤付出。我想请问下下载的歌词保存到哪里去了呢？在ds audio上倒是能看到，但在歌曲文件夹下看不到。
另一个网易的插件也是如此
谢谢您

**Comment by psychopasss** [comment]
就在歌曲同一目录。
<img width="687" alt="屏幕快照 2019-09-28 下午10 02 42" src="https://user-images.githubusercontent.com/11738089/65817586-b8a0bb00-e23b-11e9-8785-5f0926151c22.png">

**Comment by eklim530** [comment]
我的不知为何，在audio station里点击歌词能看见，但在歌曲目录下就是没有。。。无论mp3、m4a、flac什么格式都是如此。
卸载重装了插件也没用。卸载重装了audio station套件也没用。。
请问还有可能是哪方面的原因呢？谢谢您。

**Comment by psychopasss** [comment]
@eklim530 请问解决了吗。

**Comment by psychopasss** [comment]
先关闭

**Comment by psychopasss** [comment]
有问题再开

**Comment by ZHENYU64** [comment]
> 我的不知为何，在audio station里点击歌词能看见，但在歌曲目录下就是没有。。。无论mp3、m4a、flac什么格式都是如此。
> 卸载重装了插件也没用。卸载重装了audio station套件也没用。。
> 请问还有可能是哪方面的原因呢？谢谢您。

对于一些文件类型，是保存在歌曲的ID中了，就像创作人、年代、专辑信息一样。

**Comment by mwoxb** [comment]
> 我的不知为何，在audio station里点击歌词能看见，但在歌曲目录下就是没有。。。无论mp3、m4a、flac什么格式都是如此。
> 卸载重装了插件也没用。卸载重装了audio station套件也没用。。
> 请问还有可能是哪方面的原因呢？谢谢您。

对于一些文件类型，是保存在歌曲的ID中了，就像创作人、年代、专辑信息一样。
