### ISSUE TITLE
安装插件后无法显示歌词 （No lyrics）

### ISSUE THREAD

**Issue by SUIFENGSK** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#10]
安装插件1.2.2后无法显示歌词 不知道是否是因为在国外使用的原因？
之前使用旧版本 然后突然间就无法显示歌词了 现在更新到1.2.2 还是无法使用
不知道有没同样在国外使用的 有没相同的情况

**Comment by psychopasss** [comment]
我今天使用正常，在国内

**Comment by Andrewlearntocode** [comment]
> 安装插件1.2.2后无法显示歌词 不知道是否是因为在国外使用的原因？ 之前使用旧版本 然后突然间就无法显示歌词了 现在更新到1.2.2 还是无法使用 不知道有没同样在国外使用的 有没相同的情况

位置国外，群晖版本7.1，插件1.2.2安装后无法显示歌词。

**Comment by twister3344** [comment]
我的也突然用不了，但在国内

**Comment by jhanmath** [comment]
好像是QQ的接口有更新，可能得等大佬研究了

**Comment by SUIFENGSK** [comment]
@psychopasss 大佬有空检查下接口吗？

**Comment by eoun-net** [comment]
咦，很长时间不能用了。

**Comment by SUIFENGSK** [comment]
找到了另一个大佬的插件 有需要的可以自己看下 https://github.com/LightAPIs/qq_music_aum
