### ISSUE TITLE
请问下carplay不支持歌词显示是插件的问题吗？

### ISSUE THREAD

**Issue by sti4yy** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#14]
谢谢！请问下CarPlay不支持歌词显示是插件的问题吗？

**Comment by psychopasss** [comment]
应该是软件自身不支持。出于行车安全考虑，apple music也是不支持在CarPlay上看歌词的。

**Comment by sti4yy** [comment]
我发mail给群晖，他们让我去问作者。其实他们自己也不清楚到底支持不支持。
不过qq音乐啥的倒是支持歌词的。

**Comment by jazzychai** [comment]
QQ音乐好像是把歌词显示在专辑字段上了

**Comment by sunny2819** [comment]
carplay盒子播放音乐卡顿是怎么回事?

**Comment by psychopasss** [comment]
你好，播放卡顿可能与本歌词插件无关，具体可以咨询群晖官方客服。

sunny2819 ***@***.***> 于2023年4月26日周三 13:59写道：
