### ISSUE TITLE
很棒的插件！

### ISSUE THREAD

**Issue by i-iooi-i** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#3]
感谢大佬的插件，简直实用性爆炸！
另外，有个疑惑，未来会有把匹配的歌词自动下载到synology音乐目录下的可能吗？

**Comment by psychopasss** [comment]
之后有时间我看下

**Comment by i-iooi-i** [comment]
> 之后有时间我看下

嗯嗯，就是想着若是能加个判定，本地已有lrc歌词文件就不下载，本地没有歌词文件就下载一份到本地目录。这样的好处在于可以让Plexamp之类的第三方播放器调用歌词文件，在播放界面显示歌词。这样就不用仅限于群晖自带的这个Audio播放器了。
感谢。

**Comment by crystalcamel** [comment]
给大佬端茶倒水，辛苦~

**Comment by psychopasss** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/11738089/169771351-3c517ab6-3958-46c2-a72f-b18969c4096e.png">
经过调研，群晖系统为了安全，不允许插件进行文件操作，实现不了自动下载。

<img width="591" alt="image" src="https://user-images.githubusercontent.com/11738089/169772097-34d1adbf-53ab-4c3b-b5b3-d0935012904a.png">

只能在歌曲信息中，歌词tab手动下载到本地（注意mp3格式的歌曲，歌词会保存到歌曲本身标签信息中，不会另存为lrc，flac歌曲，会另存为lrc）。

[点击查看，Synology官方文档](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/AudioStation/All/enu/AS_Guide.pdf)
