### ISSUE TITLE
dsm 7 下好像存在问题

### ISSUE THREAD

**Issue by bigxianyu** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#5]
dsm7 可以手动搜索歌词，但是无法下载，如果可以使用qq搜歌词，可就太棒了~

**Comment by caelanyang** [comment]
> dsm7 可以手动搜索歌词，但是无法下载，如果可以使用qq搜歌词，可就太棒了~

我的也是 dsm7 无法自动下载，可以搜索出来在线歌词，但是无法应用。 @psychopasss 可以帮忙看一下，多谢啦

**Comment by psychopasss** [comment]
这两天我抽时间看看，工作有点忙😅

**Comment by labyte** [comment]
感谢，非常棒

**Comment by caelanyang** [comment]
> 这两天我抽时间看看，工作有点忙😅

谢谢，已 watch，坐等更新

**Comment by psychopasss** [comment]
7.0我的星际蜗牛还升级不了😵‍💫 可以拉取日志我看看吗？

**Comment by caelanyang** [comment]
> 7.0我的星际蜗牛还升级不了😵‍💫 可以拉取日志我看看吗？

可以，你稍等我，我看看怎么拉日志

**Comment by caelanyang** [comment]
> > 7.0我的星际蜗牛还升级不了😵‍💫 可以拉取日志我看看吗？
> 
> 可以，你稍等我，我看看怎么拉日志

不知道怎么拉取日志...

**Comment by bigxianyu** [comment]
> > > 7.0我的星际蜗牛还升级不了😵‍💫 可以拉取日志我看看吗？
> > 
> > 
> > 可以，你稍等我，我看看怎么拉日志
> 
> 不知道怎么拉取日志...

+1，日志中心里没有........😅

**Comment by psychopasss** [comment]
日志我也不知道咋找。。我再看看

**Comment by psychopasss** [comment]
问一个问题，你们dsm7 安装了php吗？？这个插件基于php的

**Comment by caelanyang** [comment]
> 问一个问题，你们dsm7 安装了php吗？？这个插件基于php的
有装的，群晖套件中心已安装 PHP

**Comment by tianiue** [comment]
7.0可以升级了https://www.openos.org/threads/dsm-7-0-redpill-929.3536/
等待优化歌词插件

**Comment by Stdocdure** [comment]
dsm7.0好像确实不能用

**Comment by ghost** [comment]
希望大神能够尽快解决7.0下的问题 拜托🙏

**Comment by johnchlorophyll** [comment]
Change the line 105 and 111, remove the $title. Rebuild the aum and it should be working.

```diff
-    public function getLyrics($id, $info,$title) {
+    public function getLyrics($id, $info) {
         $lrc = $this->downloadLyric($id);
         if ($this->isNullOrEmptyString($lrc)) {
             return FALSE;
         }

-        $info->addLyrics($lrc, $id, $title);
+        $info->addLyrics($lrc, $id);

         return true;
     }
```

**Comment by jhanmath** [comment]
> Change the line 105 and 111, remove the $title. Rebuild the aum and it should be working.
> 
> ```diff
> -    public function getLyrics($id, $info,$title) {
> +    public function getLyrics($id, $info) {
>          $lrc = $this->downloadLyric($id);
>          if ($this->isNullOrEmptyString($lrc)) {
>              return FALSE;
>          }
> 
> -        $info->addLyrics($lrc, $id, $title);
> +        $info->addLyrics($lrc, $id);
> 
>          return true;
>      }
> ```

@johnchlorophyll This works. Thanks!!!!

**Comment by Stdocdure** [comment]
> Change the line 105 and 111, remove the $title. Rebuild the aum and it should be working.
> 
> ```diff
> -    public function getLyrics($id, $info,$title) {
> +    public function getLyrics($id, $info) {
>          $lrc = $this->downloadLyric($id);
>          if ($this->isNullOrEmptyString($lrc)) {
>              return FALSE;
>          }
> 
> -        $info->addLyrics($lrc, $id, $title);
> +        $info->addLyrics($lrc, $id);
> 
>          return true;
>      }
> ```

大佬，用什么软件修改这个aum格式文件呢，我解压修改以后无法再次打包成aum文件了

**Comment by Stdocdure** [comment]
> > Change the line 105 and 111, remove the $title. Rebuild the aum and it should be working.
> > ```diff
> > -    public function getLyrics($id, $info,$title) {
> > +    public function getLyrics($id, $info) {
> >          $lrc = $this->downloadLyric($id);
> >          if ($this->isNullOrEmptyString($lrc)) {
> >              return FALSE;
> >          }
> > 
> > -        $info->addLyrics($lrc, $id, $title);
> > +        $info->addLyrics($lrc, $id);
> > 
> >          return true;
> >      }
> > ```
> 

你用什么软件编辑的aum格式文件呢

**Comment by johnchlorophyll** [comment]
> > > Change the line 105 and 111, remove the $title. Rebuild the aum and it should be working.
> > > ```diff
> > > -    public function getLyrics($id, $info,$title) {
> > > +    public function getLyrics($id, $info) {
> > >          $lrc = $this->downloadLyric($id);
> > >          if ($this->isNullOrEmptyString($lrc)) {
> > >              return FALSE;
> > >          }
> > > 
> > > -        $info->addLyrics($lrc, $id, $title);
> > > +        $info->addLyrics($lrc, $id);
> > > 
> > >          return true;
> > >      }
> > > ```
> 
> 你用什么软件编辑的aum格式文件呢

Use tar under Linux or Mac (install tar or use docker on Win).
[Build Script](https://github.com/psychopasss/Synology-Lrc-Plugin-For-QQ-Music/blob/master/build.sh)
Our author has put the build script in this repo.

You can also check this [link](https://github.com/johnchlorophyll/Synology-Lrc-Plugin-For-QQ-Music/blob/master/qqmusic.aum). 
I built one for myself.

**Comment by psychopasss** [comment]
我dms一直没升级，停留在6.0，谢谢上面的朋友给出解决方案。我会重新打包一个。

**Comment by Stdocdure** [comment]
感谢大佬

Stdocdure’s
