### ISSUE TITLE
群辉7.1版安装一直显示正在保存

### ISSUE THREAD

**Issue by cr15g** [psychopasss/Synology-Lrc-Plugin-For-QQ-Music#9]
群辉7.1版安装一直显示正在保存，要么提示：连接失败，请检查网络设置。这个问题怎么解决呢？

**Comment by esme518** [comment]
同样的问题...

**Comment by boboivo** [comment]
同楼上，求大神升级解决！！

**Comment by psychopasss** [comment]
我的黑群晖目前停留在6.x版本，升级不了7.x，等我周末看看。

**Comment by tbc0309** [comment]
测试估计和插件无关，群晖AudioStation版本自身bug问题，我重新打包官方自己的lyricwiki依旧同样的报错。

**Comment by tbc0309** [comment]
新测试arm64的7.1群晖AudioStation 5209版本安装插件没问题，x86_64的报错，所以静等群晖修复bug。

**Comment by tbc0309** [comment]
群晖技术支持获得最新AudioStation 5210版本：https://repo.imnks.com/群晖Synology/AudioStation-x86_64-7.0.1-5210.spk

测试已修复x86_64的bug
